apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-olkd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-olkd
    app.kubernetes.io/part-of: integ-app-gpas
  name: hacbs-test-project-olkd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-olkd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-olkd
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-erpk-tenant/integ-app-gpas/hacbs-test-project-olkd@sha256:c27ad9ab1eb7ba461061f45cc44adaa5df182b3a1c97d6d5a4bc9baac00b8389
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
